name: Deploy Shiny App

on:
  schedule:
    - cron: '0 0 */14 * *'  # Run every 14 days at midnight
  workflow_dispatch:         # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create .Renviron file
      run: |
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" > scripts/.Renviron
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./scripts
        file: ./scripts/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/shiny-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        docker run --rm \
          -e SHINYAPPS_TOKEN \
          -e SHINYAPPS_SECRET \
          ${{ secrets.DOCKERHUB_USERNAME }}/shiny-app:latest \
          R -e 'rsconnect::setAccountInfo(name="tuco-bear", token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET")); rsconnect::deployApp("/srv/shiny-server", appName="YOUR_APP_NAME", forceUpdate=TRUE)'
