name: Deploy Shiny App

on:
  schedule:
    - cron: '0 0 */14 * *'  # Run every 14 days at midnight
  workflow_dispatch:         # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libpng-dev \
          libudunits2-dev \
          libgdal-dev \
          pandoc

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c(
          "remotes",
          "rsconnect",
          "DBI",
          "dplyr",
          "leaflet",
          "lubridate",
          "plotly",
          "RPostgres",
          "RSQLite",
          "shinyjs"
        ), repos="https://cran.rstudio.com")'

    - name: Wait for existing deployments
      run: |
        sleep 30  # Wait 30 seconds for any existing deployments to complete
        
    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        max_retries=3
        retry_count=0
        while [ $retry_count -lt $max_retries ]; do
          if Rscript scripts/deploy_app.R; then
            echo "Deployment successful"
            exit 0
          else
            retry_count=$((retry_count+1))
            if [ $retry_count -lt $max_retries ]; then
              echo "Deployment failed, waiting 30 seconds before retry $retry_count of $max_retries"
              sleep 30
            else
              echo "Deployment failed after $max_retries attempts"
              exit 1
            fi
          fi
        done
