name: Deploy Shiny App

on:
  schedule:
    - cron: '0 0 */3 * *'  # Run every 3 days at midnight
  workflow_dispatch:         # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create .Renviron file
      run: |
        echo "XATA_API_KEY='${{ secrets.XATA_API_KEY }}'" > scripts/.Renviron
        
    - name: Debug - List contents
      run: |
        echo "Current directory:"
        pwd
        echo "\nDirectory contents:"
        ls -la
        echo "\nScripts directory contents:"
        ls -la scripts/
        echo "\nData directory contents:"
        ls -la data/
        
    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        echo "Starting deployment..."
        echo "Checking Docker image..."
        docker pull pythonsnatcher/shiny-app:latest
        echo "\nInspecting Docker image contents..."
        docker run --rm pythonsnatcher/shiny-app:latest ls -la /srv/shiny-server/
        echo "\nStarting deployment..."
        docker run --rm \
          -e SHINYAPPS_TOKEN \
          -e SHINYAPPS_SECRET \
          -v $(pwd)/data:/srv/shiny-server/data \
          -v $(pwd)/scripts/.Renviron:/srv/shiny-server/.Renviron \
          pythonsnatcher/shiny-app:latest \
          R -e 'print("R Session Info:"); sessionInfo(); print("Directory contents:"); list.files("/srv/shiny-server/"); print("Starting deployment..."); rsconnect::setAccountInfo(name="tuco-bear", token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET")); rsconnect::deployApp("/srv/shiny-server", appName="YOUR_APP_NAME", forceUpdate=TRUE)'
