name: Deploy Shiny App

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow
  schedule:
    - cron: "0 0 */14 * *"  # Run every 14 days at midnight UTC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Install R package dependencies
      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages("rsconnect")'

      # Run the deployment script
      - name: Run Deployment Script
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript scripts/deploy_app.R
