name: Deploy Shiny App

on:
  schedule:
    - cron: '0 0 */14 * *'  # Run every 14 days at midnight
  workflow_dispatch:         # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Create .Renviron and update data
      run: |
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" > scripts/.Renviron
        pip install -r requirements.txt  # if you have one
        python scripts/postgres_ingest.py
        
    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        docker run --rm \
          -e SHINYAPPS_TOKEN \
          -e SHINYAPPS_SECRET \
          -v $(pwd)/data:/srv/shiny-server/data \
          pythonsnatcher/shiny-app:latest \
          R -e 'rsconnect::setAccountInfo(name="tuco-bear", token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET")); rsconnect::deployApp("/srv/shiny-server", appName="YOUR_APP_NAME", forceUpdate=TRUE)'
