name: Deploy Shiny App

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow
  schedule:
    - cron: "0 0 */14 * *"  # Run every 14 days at midnight UTC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up R environment
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # Install R package dependencies
      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages("rsconnect")'

      # Deploy Shiny App
      - name: Deploy Shiny App
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          library(rsconnect)
          rsconnect::setAccountInfo(
            name = 'tuco-bear',
            token = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )
          rsconnect::deployApp(
            appDir = "scripts",      # Adjust path if necessary
            appFiles = c("app.r"),   # Ensure this is the main Shiny app file
            appName = "your-app-name",  # Replace with your actual app name
            forceUpdate = TRUE
          )
