name: Deploy Shiny App

on:
  push:
    branches: [ main ]  # or whatever your main branch is named

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libpng-dev \
          libudunits2-dev \
          libgdal-dev \
          pandoc

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("remotes", "rsconnect"), repos="https://cran.rstudio.com")'
        
    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: Rscript scripts/deploy_app.R
