name: Build Docker Image

on:
  workflow_dispatch:  # Manual trigger only - we only want to rebuild when dependencies change

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Debug - List contents before build
      run: |
        echo "Current directory:"
        pwd
        echo "\nDirectory contents:"
        ls -la
        echo "\nScripts directory contents:"
        ls -la scripts/
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./scripts
        file: ./scripts/Dockerfile
        push: true
        tags: pythonsnatcher/shiny-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Debug - Check Docker image
      run: |
        echo "Pulling image to verify contents..."
        docker pull pythonsnatcher/shiny-app:latest
        echo "\nInspecting Docker image contents:"
        docker run --rm pythonsnatcher/shiny-app:latest ls -la /srv/shiny-server/
        echo "\nChecking R installation:"
        docker run --rm pythonsnatcher/shiny-app:latest R --version
