name: Build Docker Image

on:
  workflow_dispatch:  # Manual trigger only - we only want to rebuild when dependencies change

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug - Environment Info
      run: |
        echo "GitHub Workspace: $GITHUB_WORKSPACE"
        echo "GitHub Reference: $GITHUB_REF"
        echo "GitHub SHA: $GITHUB_SHA"
        
    - uses: actions/checkout@v3
    
    - name: Debug - Repository Contents
      run: |
        echo "=== Full Repository Structure ==="
        tree .
        echo "\n=== Current Directory ==="
        pwd
        echo "\n=== Root Directory Contents ==="
        ls -la
        echo "\n=== Scripts Directory Contents ==="
        ls -la scripts/ || echo "Scripts directory not found!"
        echo "\n=== Dockerfile Location Check ==="
        if [ -f "./scripts/Dockerfile" ]; then
          echo "Dockerfile found at ./scripts/Dockerfile"
          cat ./scripts/Dockerfile
        else
          echo "ERROR: Dockerfile not found at ./scripts/Dockerfile"
        fi
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Debug - Docker Info
      run: |
        echo "=== Docker Version ==="
        docker version
        echo "\n=== Docker Info ==="
        docker info
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Debug - Docker Hub Login Check
      run: |
        echo "=== Testing Docker Hub Authentication ==="
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} 2>&1 | grep "Login Succeeded" || echo "Login verification failed"
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./scripts
        file: ./scripts/Dockerfile
        push: true
        tags: pythonsnatcher/shiny-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Debug - Post Build Checks
      run: |
        echo "=== Pulling Image ==="
        docker pull pythonsnatcher/shiny-app:latest
        echo "\n=== Image Details ==="
        docker images | grep pythonsnatcher/shiny-app
        echo "\n=== Image Inspection ==="
        docker inspect pythonsnatcher/shiny-app:latest
        echo "\n=== Container File System Check ==="
        docker run --rm pythonsnatcher/shiny-app:latest ls -la /srv/shiny-server/
        echo "\n=== R Version Check ==="
        docker run --rm pythonsnatcher/shiny-app:latest R --version
        echo "\n=== Container Environment Variables ==="
        docker run --rm pythonsnatcher/shiny-app:latest env
        
    - name: Debug - Final Status
      if: always()
      run: |
        echo "=== Workflow Status ==="
        echo "Job Status: ${{ job.status }}"
        echo "Runner OS: ${{ runner.os }}"
        echo "Workspace: ${{ github.workspace }}"
