name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Start Workflow
      run: |
        echo "::group::Starting Workflow"
        echo "Time: $(date)"
        echo "Runner: ${{ runner.os }}"
        echo "::endgroup::"
    
    - uses: actions/checkout@v3
    
    - name: Debug - Pre-build Environment
      run: |
        echo "::group::Environment Check"
        echo "=== Working Directory ==="
        pwd
        echo -e "\n=== Repository Contents ==="
        ls -R
        echo -e "\n=== Environment Variables ==="
        env
        echo "::endgroup::"
        
    - name: Docker Setup Check
      run: |
        echo "::group::Docker Setup"
        echo "=== Docker Version ==="
        docker version
        echo -e "\n=== Docker Info ==="
        docker info
        echo -e "\n=== Docker Images ==="
        docker images
        echo "::endgroup::"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Verify Docker Hub Login
      run: |
        echo "::group::Docker Hub Authentication"
        echo "Checking Docker Hub login status..."
        docker info | grep Username || echo "Not logged in to Docker Hub"
        echo "::endgroup::"
        
    - name: Build Docker image
      uses: docker/build-push-action@v4
      id: docker_build
      with:
        context: ./scripts
        file: ./scripts/Dockerfile
        push: false
        tags: pythonsnatcher/shiny-app:latest
        load: true
        no-cache: true
        buildkitd-flags: --debug
        provenance: false
        
    - name: Build Verification
      run: |
        echo "::group::Build Verification"
        echo "=== Local Images ==="
        docker images
        echo -e "\n=== Image Details ==="
        docker inspect pythonsnatcher/shiny-app:latest || echo "Failed to inspect image"
        echo -e "\n=== Image History ==="
        docker history pythonsnatcher/shiny-app:latest || echo "Failed to get image history"
        echo "::endgroup::"
        
    - name: Push to Docker Hub
      if: success()
      uses: docker/build-push-action@v4
      with:
        context: ./scripts
        file: ./scripts/Dockerfile
        push: true
        tags: pythonsnatcher/shiny-app:latest
        provenance: false
        
    - name: Push Verification
      if: success()
      run: |
        echo "::group::Push Verification"
        echo "=== Pulling Image ==="
        docker pull pythonsnatcher/shiny-app:latest
        echo -e "\n=== Remote Image Details ==="
        docker images pythonsnatcher/shiny-app:latest --format "{{.Repository}}:{{.Tag}} - Size:{{.Size}}"
        echo "::endgroup::"

    - name: Error Logging
      if: failure()
      run: |
        echo "::group::Error Information"
        echo "=== Docker System Info ==="
        docker system info
        echo -e "\n=== Docker Hub Connection Test ==="
        curl -v https://registry.hub.docker.com/v2/ 2>&1
        echo -e "\n=== Dockerfile Contents ==="
        cat ./scripts/Dockerfile || echo "Dockerfile not found"
        echo -e "\n=== Directory Structure ==="
        find . -type f -name "Dockerfile" 2>/dev/null
        echo "::endgroup::"

    - name: Completion Status
      if: always()
      run: |
        echo "::group::Workflow Completion"
        echo "Time: $(date)"
        echo "Final Status: ${{ job.status }}"
        echo "::endgroup::"
