name: Generate Directory Tree

on:
  schedule:
    - cron: '0 0 */21 * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate directory tree
        run: |
          sudo apt-get install tree
          tree -L 2 > DIRECTORY_STRUCTURE.md

      - name: Commit directory tree
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update directory structure"
