name: Render Shiny App

on:
  schedule:
    - cron: '0 0 1,15 * *'  # Runs on 1st and 15th of every month
  workflow_dispatch:  # Allows manual trigger
  push:
    paths:
      - 'scripts/dashboard.Rmd'  # Trigger on changes to the Rmd file

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for git operations
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'
        
    - name: Set up Pandoc
      uses: r-lib/actions/setup-pandoc@v2
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        
    - name: Install R dependencies
      run: |
        R -e 'install.packages(c(
          "shiny",
          "plotly",
          "dplyr",
          "leaflet",
          "shinyjs",
          "RSQLite",
          "rmarkdown",
          "flexdashboard"
        ), repos = "https://cloud.r-project.org")'
        
    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: ${{ runner.os }}-r-
        
    - name: Render Shiny app to HTML
      run: |
        R -e "rmarkdown::render('scripts/dashboard.Rmd', 
              output_format = 'html_document',
              output_dir = '.',
              output_file = 'index.html',
              runtime = 'shiny')"
              
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        force_orphan: true  # Create a new history for gh-pages branch
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add index.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update dashboard [skip ci]" && git push)
