name: Scrape

on:
  pull_request:
    types:
      - opened
  schedule:
  - cron: '*/48 * * * *'  # Schedule to run every 10 minutes

  workflow_dispatch:  # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml gspread oauth2client pandas

      - name: Run Python script
        run: python scripts/main.py
