name: Scrape

on:
  pull_request:
    types:
      - opened
  schedule:
    - cron: '*/48 * * * *'  # Schedule to run every 48 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml gspread oauth2client pandas pytz

      - name: Run Python script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python scripts/main.py
